services:
  db:
    platform: linux/amd64
    image: postgres:17-alpine
    volumes:
      - C:/Program Files/PostgreSQL/17/data:/var/lib/postgresql/data
    command: postgres -c dynamic_shared_memory_type=posix
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JoysellSticks15@
      POSTGRES_DB: frontend
      POSTGRES_INITDB_ARGS: '--nosync'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    environment:
      DB_HOST: db # Важно: имя сервиса, не localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: JoysellSticks15@
      DB_NAME: frontend
    env_file:
      - ./server/.env
    ports:
      - '8080:8080'
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '4173:4173'
    depends_on:
      - server
    command: npm run preview
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
